package org.usfirst.frc.team7414.robot.Monitors;

public enum FaultType {
    SOLENOIDFAULT, COMPRESSORFAULT, UNDERCURRENTFAULT, OVERCURRENTFAULT, UNDERVOLTAGEFAULT, OVERVOLTAGEFAULT, TEMPERATUREFAULT
}